# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
     - uses: actions/checkout@v2
     - name: Set up Ruby 3.0
       uses: actions/setup-ruby@v1
       with:
        ruby-version: 3.0.x
     - name: Install bundler
       run: |
         gem install bundler
         bundle install --jobs 4 --retry 3
     - name: Run rubocop
       run: bundle exec rake lint
     - name: Run tests
       run: bundle exec rake test   
     - name: Upload coverage results
       uses: actions/upload-artifact@v1
       with:
        name: coverage-report
        path: coverage
